# -*- coding: utf-8 -*-
"""sampleWebScrap.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zyL_2EJAM1ORAJG3oTwLdZ5_sTr7KRBw
"""

pip install requests beautifulsoup4

import requests

# Define the URL of the website to scrape
url = 'https://news.google.com/home?hl=en-US&gl=US&ceid=US:en'  # Replace with the actual URL

# Send a GET request to the webpage
response = requests.get(url)

# Check if the request was successful
if response.status_code == 200:
    html_content = response.text
else:
    print(f"Failed to retrieve the webpage. Status code: {response.status_code}")

from bs4 import BeautifulSoup

# Parse the HTML content using BeautifulSoup
soup = BeautifulSoup(html_content, 'html.parser')

# Extract the article titles
# Assuming the titles are within <h2> tags with a class 'title' (you'll need to inspect the actual HTML structure of your target website)
article_titles = soup.find_all('h2', class_='title')

# Print the extracted titles
for title in article_titles:
    print(title.get_text())

article_titles = soup.find_all('div', class_='article')
for article in article_titles:
    title = article.find('a').get_text()
    print(title)

import requests
from bs4 import BeautifulSoup

# Define the URL of the website to scrape
url = 'https://news.google.com/home?hl=en-US&gl=US&ceid=US:en'  # Replace with the actual URL

# Send a GET request to the webpage
response = requests.get(url)

# Check if the request was successful
if response.status_code == 200:
    html_content = response.text

    # Parse the HTML content using BeautifulSoup
    soup = BeautifulSoup(html_content, 'html.parser')

    # Inspect the HTML structure to find the right tag and class
    # Let's assume titles are within <h2> tags with class 'headline' and contain <a> tags
    article_titles = soup.find_all('a', class_='gPFEn')

    # Check if we found any titles
    if article_titles:
        # Print the extracted titles
        for title in article_titles:
            title_text = title.find('a').get_text() if title.find('a') else title.get_text()
            print(title_text)
    else:
        print("No article titles found. Please inspect the HTML structure.")
else:
    print(f"Failed to retrieve the webpage. Status code: {response.status_code}")

